title: PDB database demo
author: John, Li, Xi, Lucy, Xinchun
email: zhongyueyang20@gmail.com
theme: jekyll-theme-tactile
description: > # this means to ignore newlines until "baseurl:"
  Demo for the construction of IntEnzyDB, a database for storing enzyme kinetics-structure data. 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage