title: IntEnzyDB
author: John, Li, Xi, Lucy, Xinchun
email: zhongyue.yang@vanderbilt.edu
theme: minima:
       skin: dark
#theme: jekyll-theme-architect
description: > # this means to ignore newlines until "baseurl:"
  Whenever you commit to this repository, GitHub Pages will run Jekyll to rebuild the pages in your site, from the content in your Markdown files. 
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ZJYgrp # DO NOT include the @ character, or else the build will fail!
# github: https://github.com/ZJYgrp/database_construction
show_excerpts: true # set to false to remove excerpts on the homepage
# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true
avatar: "./pics/logo.png"
# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
title-img: ./pics/protein.jpeg
